### ISSUE TITLE
您好，请问这个ios应该怎么配idl-license，安卓可以运行了，但是ios一直卡在把脸移入框内或请对准手机。第一次弄ios的，不太熟

### ISSUE THREAD

**Issue by huntiantao** [gwsh/baidu_face_flutter#2]
您好，请问这个ios应该怎么配idl-license，安卓可以运行了，但是ios一直卡在把脸移入框内或请对准手机。第一次弄ios的，不太熟

**Comment by gwsh** [comment]
打开xcode add file  选择ios的 license 记住要 检查Bid 保持一致

**Comment by gwsh** [comment]
> 您好，请问这个ios应该怎么配idl-license，安卓可以运行了，但是ios一直卡在把脸移入框内或请对准手机。第一次弄ios的，不太熟

打开xcode add file 选择ios的 license 记住要 检查Bid 保持一致
