### ISSUE TITLE
你好，这个插件无法安装

### ISSUE THREAD

**Issue by chinafelix** [gwsh/baidu_face_flutter#3]
![image](https://user-images.githubusercontent.com/20641047/99142661-27381680-2692-11eb-8bae-d3cd62cbe15d.png)

flutter packages pub get 的时候，无法安装依赖；

**Comment by gwsh** [comment]
> ![image](https://user-images.githubusercontent.com/20641047/99142661-27381680-2692-11eb-8bae-d3cd62cbe15d.png)
> 
> flutter packages pub get 的时候，无法安装依赖；

请你发一下你的pubspec.yaml

**Comment by chinafelix** [comment]
![image](https://user-images.githubusercontent.com/20641047/99142837-ce697d80-2693-11eb-8086-8e64d9802fd3.png)

**Comment by gwsh** [comment]
@chinafelix  请用git 引用暂时没有发布到 pub

**Comment by chinafelix** [comment]
我直接把你的代码clone下来，example里的例子运行出错，直接修改了你的ke y.properties下的storeFile：

![image](https://user-images.githubusercontent.com/20641047/99207668-89f7f200-27f9-11eb-9459-ca612bb93851.png)

![image](https://user-images.githubusercontent.com/20641047/99207651-79e01280-27f9-11eb-94ff-a30e522dbe7a.png)

**Comment by gwsh** [comment]
> 我直接把你的代码clone下来，example里的例子运行出错，直接修改了你的ke y.properties下的storeFile：
> 
> ![image](https://user-images.githubusercontent.com/20641047/99207668-89f7f200-27f9-11eb-9459-ca612bb93851.png)
> 
> ![image](https://user-images.githubusercontent.com/20641047/99207651-79e01280-27f9-11eb-94ff-a30e522dbe7a.png)

请添加我的qq 我发给你example的 key.kjs

**Comment by gwsh** [comment]
> 我直接把你的代码clone下来，example里的例子运行出错，直接修改了你的ke y.properties下的storeFile：
> 
> ![image](https://user-images.githubusercontent.com/20641047/99207668-89f7f200-27f9-11eb-9459-ca612bb93851.png)
> 
> ![image](https://user-images.githubusercontent.com/20641047/99207651-79e01280-27f9-11eb-94ff-a30e522dbe7a.png)

673560736
